version: "3.7"
services:
  frontend:
    build:
      context: frontend
      dockerfile: ./frontend.dockerfile
    container_name: bad_words_frontend
    restart: on-failure
    ports:
      - 4200:80

  backend:
    build:
      context: backend
      dockerfile: ./backend.dockerfile
    container_name: bad_words_backend
    restart: on-failure
    ports:
      - 4201:80
